version: '3'
services:
  app:
    build: docker/app
    ports:
    - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://blog-springboot_db_1:3306/blog
  db:
    image: mysql:5.7.22
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springuser
      MYSQL_DATABASE: blog